name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build for js
      run: sbt JsDev/fastOptJS
    - uses: actions/upload-artifact@v1
      with:
        name: fastopt.js
        path: target/JsDev/target/scala-2.13/jsdev-fastopt.js
